/** @typedef {import('/markup/experimental/es/types').Token} TokenizerToken */
/** @typedef {IterableIterator<TokenizerToken>} TokenizerTokens */
/** @typedef {import('/markup/experimental/es/types').Match} TokenizerMatch */
/** @typedef {import('/markup/experimental/es/types').Capture} TokenizerCapture */
/** @typedef {import('/markup/experimental/es/types').Group} TokenizerGroup */
/** @typedef {import('/markup/experimental/es/types').Groups} TokenizerGroups */
/** @typedef {import('/markup/experimental/es/types').Goal} TokenizerGoal */
/** @typedef {import('/markup/experimental/es/types').Context} TokenizerContext */
/** @typedef {import('/markup/experimental/es/types').Contexts} TokenizerContexts */
/** @typedef {import('/markup/experimental/es/types').State} TokenizerState */
